# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: utils
    init: |
      echo -e "\033[1;44mSome useful commands\033[0m"
      echo -e "\033[1;32mNode.js\033[0m"
      node -e "console.log(require('os').version())"
      echo -e "\033[1;33mGitpod\033[0m"
      gp info
      gp top
      echo -e "\033[1;31mMySQL\033[0m"
      echo -e "\033[0;32mGenerate hash for access token\033[0m"
      node -e "console.log(require('crypto').createHash('sha3-256').update('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx').digest('hex'))"
      echo -e "\033[0;32mmMySQL dump and restore\033[0m"
      echo "docker exec db-mysql /usr/bin/mysqldump --databases -u root --password=secret idm > backup.sql"
      echo "cat backup.sql | docker exec -i db-mysql /usr/bin/mysql -u root --password=secret idm"
      echo -e "\033[1;34mMQTT\033[0m"
      docker exec mqtt-broker mosquitto_pub -t "telegraf/sensor/01" -m '{"id":"TT001","temperature":24}'
      docker exec mqtt-broker mosquitto_sub -t "telegraf/#"
      echo -e "\033[1;36mDocker\033[0m"
      docker exec -it db-mysql /bin/bash
      (gp ports list 2> /dev/null) || true
      docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep "unhealthy"
  - name: build
    init: docker compose pull # runs during prebuild
    command: |
      sudo chown -R 472:472 grafana/.db
      sudo chown -R 1000:1000 node-red/data
      echo Welcome to FIWARE
      docker compose down -v --remove-orphans
      docker compose up -d --remove-orphans --build
      echo Waking up FIWARE Node-RED app on Replit...
      curl https://fiware.zeldalegends.repl.co/gitpod -d url=$(node -e "console.log(require('process').env.GITPOD_WORKSPACE_URL)")
      docker compose logs fiware-orion -f

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - description: NGSI-LD @context files
    port: 80
    onOpen: ignore
    visibility: public
  - description: Orion Context Broker
    port: 1026
    onOpen: ignore
  - description: PEP Proxy (Orion)
    port: 1027
    onOpen: ignore
    visibility: public
  - description: Orion-LD Context Broker
    port: 1028
    onOpen: ignore
  - description: PEP Proxy (Orion-LD)
    port: 1029
    onOpen: ignore
    visibility: public
  - description: Node-RED
    port: 1880
    onOpen: ignore
    visibility: public
  - description: PEP Proxy (Node-RED)
    port: 1881
    onOpen: ignore
    visibility: public
  - description: Mosquitto MQTT Broker
    port: 1883
    onOpen: ignore
    visibility: public
  - description: Grafana Enterprise
    port: 3000
    onOpen: ignore
    visibility: public
  - description: Keyrock IdM
    port: 3005
    onOpen: ignore
    visibility: public
  - description: MySQL DB
    port: 3306
    onOpen: ignore
  - description: IoT Agent (North Port)
    port: 4041
    onOpen: ignore
  - description: Truffle Suite's Ganache
    port: 7545
    onOpen: ignore
    visibility: public
  - description: IoT Agent (South Port)
    port: 7896
    onOpen: ignore
  - description: MongoExpress
    port: 8081
    onOpen: ignore
    visibility: public
  - description: Influx DB
    port: 8086
    onOpen: ignore
    visibility: public
  - description: Telegraf healthcheck
    port: 8125
    onOpen: ignore
    visibility: public
  - description: MQTT over Websocket
    port: 9001
    onOpen: ignore
    visibility: public
  - description: Cassandra DB
    port: 9042
    onOpen: ignore
  - description: Mongo DB
    port: 27017
    onOpen: ignore

#  - description: Tutorial App context data
#    port: 3000
#    onOpen: ignore | notify | open-browser | open-preview
#    visibility: public
#  - description: Tutorial Devices over HTTP
#    port: 3001
#    onOpen: ignore
#  - description: Express web application
#    port: 8000
#    onOpen: ignore
#  - description: PEP Proxy (Express App)
#    port: 8001
#    onOpen: ignore
#    visibility: public
#  - description: Simple web application
#    port: 8082
#    onOpen: ignore
#    visibility: private
#  - description: PEP Proxy (Web App)
#    port: 8083
#    onOpen: ignore
#    visibility: public

