services:
  orion:
    image: fiware/orion #:3.0.0
    hostname: orion
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo -logLevel DEBUG

  orion-ld:
    image: fiware/orion-ld #:1.1.0
    hostname: orion-ld
    ports:
      - "1028:1026" # localhost:1028
    command: -dbhost mongo -db orionld -logLevel DEBUG

  mongo:
    image: mongo #:4.4
    hostname: mongo
    ports:
      - "27017:27017" # localhost:27017
    command: --nojournal
    
  mongo-express:
    image: mongo-express #:1.0.0-alpha
    hostname: mongo-express
    ports:
      - "8081:8081" # localhost:8081

  node-red:
    image: nodered/node-red #:3.0.2
    hostname: node-red
    ports:
      - "1880:1880" # localhost:1880